# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/carts/add/ HTTP/1.1
content-type: application/json
Authorization: 84b505e383c67d36f50c8490a5ea8709cb57dbc49b5ce2ba48014cc504f6

{
	"product": 10,
	"quantity": 5,
	"item": 1
}