# Generated by Django 3.2.4 on 2021-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Telephone'),
        ),
    ]
